patch:
  menu:
    page_size: 7
  schema_list:
    - schema: terra_pinyin
  style:
    color_scheme: nord
  preset_color_schemes:
    nord:
      name: Nord-DC
      text_color: 0xdcdcdc
      back_color: 0x2e3440
      border_color: 0x4c566a
      hilited_candidate_text_color: 0xdcdcdc
      hilited_candidate_back_color: 0x88c0d0
  
  
